name: methylkit

channels:
  - conda-forge
  - bioconda

dependencies:
  - bioconda::bioconductor-chippeakanno=3.44.0
  - bioconda::bioconductor-genomation=1.42.0
  - bioconda::bioconductor-methylkit=1.36.0
  - bioconda::bioconductor-rtracklayer=1.70.1
  - bioconda::bioconductor-txdb.hsapiens.ucsc.hg38.knowngene=3.22.0
  - conda-forge::h5py=3.16.0
  - conda-forge::natsort=8.4.0
  - conda-forge::numpy=2.5.3
  - conda-forge::pandas=3.0.6
  - conda-forge::python=3.15.0
  - conda-forge::r-base=4.5.3
  - conda-forge::r-optparse=1.8.2
  - conda-forge::rpy2=3.6.8
